---
title: '410873056'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## package
```{r}
library(googlesheets4)
```
```{r}
install.packages(c("dplyr", "lubridate"))

```
```{r}
a <- 2
a = 2 # = 與 <-同義 
```
```{r}
a
```
```{r}
3 -> b
```
```{r}
my_108_total_credits <- 15
```
```{r}
my_108_total_credits
```
```{r}
`我的108學年總學分數` <- 15
```
```{r}
`我的108學年總學分數`
```
```{r}
我的108學年總學分數 = 5
```
```{r}
我的108學年總學分數 
```
```{r}
`我的年紀`<-20
my_age<-`我的年紀`
```
```{r}
says<-c('"你媽確診"')
```
```{r}
library(httr)
library(dplyr)
GET("https://github.com/clive0305/108-2-56-inclass-practice")%>%
  content() %>%
  View() 
```
```{r}
library(googlesheets4)
`出席狀況表單網址` <- "https://docs.google.com/spreadsheets/d/1EAG49qDKPWWi0ebkVr29TLrvVnoBPfkvxYY-J3xLAHY/edit?usp=drive_open&ouid=102488507875366675447 "# 缺乏定義值
ss <- as_sheets_id(`出席狀況表單網址`)
homework_sheet <- sheets_read(ss,sheet=1)
```
'
```{r}
vectorExample <- c(2, 6, 7)
listExample <- list(2, 6, 7)
print(vectorExample)
print(listExample)
```
```{r}
library(lubridate)
`小明交易1` <- list(
  ymd_hms("2020-03-31T13:40:55Z"), # Date/Time class
  "一芳", # character
  2, # numeric
  "水果茶" # character
)
print(`小明交易1`)
```
```{r}
# list含兩個vectors
`小明108學年課表A` <- list(
  c("108-1","高級會計學","高等統計學"),
  c("108-2","食在拉丁美洲")
)
print(`小明108學年課表A`)
```
```{r}
`weather`=list( 
   `台北市氣溫`=list(
   time=ymd("2020-03-31","2020-04-01"),
   `台北市`=list(
   `the highest temperature`=25,
   `the lowest temperature`=18)
  ),
   `新北市氣溫`=list(
   time=ymd("2020-03-31","2020-04-01"),
   `新北市`=list(
   `the highest temperature`=24,
   `the lowest temperature`=15)
  )
 )
print(weather)
```


```{r}
# list含兩個lists, 子層list又各含兩個vectors
`小明108學年課表C` <- list(
  `108學年第1學期`=list(
    c("108-1"), # 可只寫 "108-1"
    c("高級會計學","高等統計學")
       ),
  `108學年第2學期`=list(
    c("108-2"),
    c("食在拉丁美洲")
  )
)
print(`小明108學年課表C`)
```
```{r}
# 10位學生的主系
majors10_char <- c('經濟學系','社會學系','社會學系','經濟學系','經濟學系','社會學系','經濟學系','經濟學系','經濟學系','社會學系')

typeof(majors10_char)
class(majors10_char)
```
```{r}
taiwan_time <- "西元2019年4月12日 12點55分30秒"
oslo_time <- "18.11.2018 15:33:02"
```


```{r}
tpeTime <- 
  ymd_hms(
    c("2020-03-18 13:52:40","2020-03-11 03:12:40"),
    tz="Asia/Taipei"
    )
pgTime <- mdy_hms("Mar.18, 2020, 05:52:40",
                  tz="Europe/Lisbon")
with_tz(tpeTime, tzone="Europe/Paris")
with_tz(pgTime, tzone="Europe/Paris")
```
```{r}

source("https://www.dropbox.com/s/mk7bxvu6a3lxf79/studentEnvironmentReport.R?dl=1",print.eval = T)
```
```{r}
library(jsonlite)
fromJSON("http://data.ntpc.gov.tw/api/v1/rest/datastore/382000000A-000157-002",
         simplifyDataFrame = F) -> newTaipeiCityVaccine
```
```{r}
str(newTaipeiCityVaccine)
name(newTaipeiCityVaccine)
length(newTaipeiCityVaccine)
```
```{r}
listExample <- 
  list(
    student="小明",
    `學期`=list(
      `108-1`=list(
        list(
          name="個體經濟學",
          teacher="Alice",
          grade=85
        )
      ),
      `108-2`=list(
        list(
          name="總體經濟學",
          teacher="Mark",
          grade=78
        )
      )
    )
  )
# 有多少位置可選：
length(listExample)
```
```{r}
vectorExample <- c("小明","小英","大雄")

# 有多少位置可選：
length(vectorExample)
```
```{r}
vectorExample
vectorExample[c(1,3)]
vectorExample[c(3,2,1)] # 產生重新排列效果
```
```{r}
# 顯示到第一層
str(listExample, max.level=1)

listExample[c(1,2)]
```
```{r}
listExample <- 
  list(
    student="小明",
    `學期`=list(
      `108-1`=list(
        list(
          name="個體經濟學",
          teacher="Alice",
          grade=85
        )
      ),
      `108-2`=list(
        list(
          name="總體經濟學",
          teacher="Mark",
          grade=78
        )
      )
    )
  )
# 有多少位置可選：
length(listExample)
```
```{r}
# 有多少名字可選：
names(listExample)

```
```{r}
a <- c("1","b","TRUE")
a[[2]] <- "c" # 元素存在: 替換
a[[4]] <- "7" # 元素不存在： 增加
a[c(5,6)] <- c("J", "K")
a[[7]] <- "Johnson"
a <- c(a, "Mary")
print(a)
```
```{r}
library(lubridate)
list1 <- 
  list(
    list(
      name="Jack",
      birthday=ymd("1998-03-21"),
      status=c(height=177, weight=80)
    )
  )

str(list1)
```
```{r}
# 更改日期
list1[[1]]$birthday <- ymd("1997-03-21")

# 新增資料
list1[[2]] <- list(
  name="Mary",
  birthday=ymd("1998-08-24")
)

str(list1)
```
```{r}
print(a)
a[-c(1,3)]
a[c(-2)]

print(a)
a[-c(1,3)] -> a # 要回存才算真的刪除
```




